# Generated by Django 5.1 on 2025-03-26 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('kategori', models.CharField(max_length=100)),
                ('harga', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nama_restoran', models.CharField(max_length=200)),
                ('lokasi', models.CharField(max_length=300)),
                ('url_gambar', models.URLField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
