# Generated by Django 5.1 on 2025-03-26 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('katalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='url_gambar',
            new_name='img_link',
        ),
        migrations.RemoveField(
            model_name='product',
            name='lokasi',
        ),
        migrations.RemoveField(
            model_name='product',
            name='nama_restoran',
        ),
        migrations.AddField(
            model_name='product',
            name='deskripsi',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='nama',
            field=models.CharField(max_length=255),
        ),
    ]
