# Generated by Django 5.1.7 on 2025-03-27 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cart_items',
            field=models.ManyToManyField(related_name='orders', to='checkout.cart'),
        ),
    ]
